services:
  fetcher-mcp:
    build:
      context: .
      dockerfile: ./apps/fetcher/Dockerfile
    container_name: fetcher-mcp
    command: bun dev
    stdin_open: true # stdinを開いたままにする
    tty: true # 疑似TTYを割り当てる
    networks:
      - mcp-network

  filesystem-mcp:
    build:
      context: .
      dockerfile: ./apps/filesystem/Dockerfile
    container_name: filesystem-mcp
    command: bun dev
    env_file:
      - path: ./.env
        required: true
    volumes:
      - ./apps/filesystem/outputs:/app/apps/filesystem/outputs
    stdin_open: true # stdinを開いたままにする
    tty: true # 疑似TTYを割り当てる
    networks:
      - mcp-network

  notion-mcp:
    build:
      context: .
      dockerfile: ./apps/notion/Dockerfile
    container_name: notion-mcp
    command: bun dev
    env_file:
      - path: ./.env
        required: true
    stdin_open: true # stdinを開いたままにする
    tty: true # 疑似TTYを割り当てる
    networks:
      - mcp-network

  slack-mcp:
    build:
      context: .
      dockerfile: ./apps/slack/Dockerfile
    container_name: slack-mcp
    command: bun dev
    env_file:
      - path: ./.env
        required: true
    stdin_open: true # stdinを開いたままにする
    tty: true # 疑似TTYを割り当てる
    networks:
      - mcp-network

networks:
  mcp-network:
    name: mcp-network
    driver: bridge
